use html_scraper;
CREATE TABLE DATA (
     ID BIGINT NOT NULL AUTO_INCREMENT,
     HD TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     DATA LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     TMSP TIMESTAMP,
     RTSMP TEXT CHARACTER  SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     CAT1 VARCHAR(10) NOT NULL,
     CAT2 VARCHAR(10) NOT NULL,
     IMAGEURL TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     LOC_PATH TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     LOC VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     LINK TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     LANG1 VARCHAR(10) NOT NULL,
     LANG2 VARCHAR(10) NOT NULL,
     VID VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT 'NIL',
     GRP BIGINT NOT NULL DEFAULT '0',
TAGS LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
API_FLAG BIGINT NOT NULL DEFAULT '0',
TYPE_CAT VARCHAR(10) NOT NULL,
     primary key (id),
     UNIQUE KEY `LINK` (`LINK`(200))
);
