CREATE TABLE LINK_MASTER (
     id BIGINT NOT NULL AUTO_INCREMENT,
     LINK TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
     ACT VARCHAR(3),
     PRIMARY KEY (id),
     CAT1 VARCHAR(20) NOT NULL,
     CAT2 VARCHAR(20) NOT NULL,
     LOC VARCHAR(20) NOT NULL,   
     LANG1 VARCHAR(10) NOT NULL,
     LANG2 VARCHAR(10) NOT NULL DEFAULT 'N/A',
TYPE_CAT VARCHAR(10) NOT NULL,
FREQUENCY VARCHAR(10) NOT NULL,
     UNIQUE KEY `LINK` (`LINK`(200))
);
